server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.5.136:3306/dianping?characterEncoding=UTF8&autoReconnect=true&useSSL=true
    url: jdbc:mysql://192.168.1.19:3306/dianping?characterEncoding=UTF8&autoReconnect=true&useSSL=true
    username: user
    password: password
  redis:
#    host: 192.168.5.136
    host: 192.168.1.19
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug

rocketmq:
  name-server: 192.168.1.19:9876
  producer:
    secret-key: 12345678
    access-key: rocketmq2
    group: asyn-2-group
  consumer:
    secret-key: 12345678
    access-key: rocketmq2
    group: asyn-2-group