---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by limengyuan.
--- DateTime: 2023/7/30 16:56
---

-- 订单id
local voucherId = ARGV[1]
-- 用户id
local userId = ARGV[2]
-- 订单id
local orderId = ARGV[3]
-- 优惠券key
local stockKey = 'seckill:stock:' .. voucherId
-- 订单key
local orderKey = 'seckill:order:' .. voucherId
-- 判断库存是否充足
-- 获取 Redis 中的库存数量
local stockValue = tonumber(redis.call('get', stockKey))

-- 判断库存是否充足
if (stockValue <= 0) then
    return 1
end
-- 判断用户是否下单
if (redis.call('sismember', orderKey, userId) == 1) then
    return 2
end
-- 扣减库存
redis.call('incrby', stockKey, -1)
-- 将userId存入当前优惠券的set集合
redis.call('sadd', orderKey, userId)
redis.call("xadd","stream.orders","*","userId",userId,"voucherId",voucherId,"id",orderId)
return 0